-- set runtimepath+=~/.config/nvim
-- let g:UltiSnipsEditSplit="horizontal"
-- let g:UltiSnipsUsePythonVersion = 3
-- let g:UltiSnipsSnippetsDir = '~/.config/nvim/UltiSnips/'
-- let g:UltiSnipsSnippetDirectories = ['~/.config/nvim/UltiSnips', 'UltiSnips']
-- let g:UltiSnipsExpandTrigger="<tab>"
-- let g:UltiSnipsJumpForwardTrigger="<tab>"
-- let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
