require('lsp.servers.bashls')
require('lsp.servers.cssls')
require('lsp.servers.dockerls')
require('lsp.servers.eslint')
require('lsp.servers.gopls')
require('lsp.servers.html')
require('lsp.servers.jsonls')
require('lsp.servers.lua')
require('lsp.servers.pyright')
require('lsp.servers.solargraph')
-- require('lsp.servers.sorbet')
require('lsp.servers.sqls')
require('lsp.servers.tsserver')
require('lsp.servers.vimls')
require('lsp.servers.vuels')
require('lsp.servers.yamlls')
